### ISSUE TITLE
Bug: WebUI - Frontend & Backend hostnames get inverted when creating new remote sites

### ISSUE THREAD

**Issue by OlofBlomqvist** [OlofBlomqvist/odd-box#30]
(version: 0.1.7-preview+)

When creating a new remote site in the web ui, the frontend and backend gets inverted on save

![one](https://github.com/user-attachments/assets/6c5ebd74-2f28-4a1b-9a8d-192fd2956c6d)
![image](https://github.com/user-attachments/assets/383f15b0-4546-433b-8553-c48f348f6247)

**Comment by Jonas-PFX** [comment]
This has now been fixed.
