### ISSUE TITLE
feature request - webui hosted proc args

### ISSUE THREAD

**Issue by OlofBlomqvist** [OlofBlomqvist/odd-box#40]
When one wants to add an argument before any existing ones, you need to remove the existing ones and add them back - would be nice if we could insert variables in the correct place and possibly be able to move the order around as well

**Comment by Jonas-PFX** [comment]
I've been testing a few different ways to handle env variables and arguments and I think the best way for this might just be a simple semicolon separated text input. I've switched to that for now, but will keep this request in mind if we switch to another way of handling these config items sometime later.
