### ISSUE TITLE
Basic Web UI

### ISSUE THREAD

**Issue by OlofBlomqvist** [OlofBlomqvist/odd-box#6]
It would be nice to have a web interface for odd-box such that one can opt out of the TUI and still be able to control site status and access log data. A web interface would also be a good place to allow for updating/adding/removing site configurations and possibly global settings as well, which would be less practical in the TUI.

I imagine this would be useful when running odd-box as a background service but possibly just provides a better user experience over-all for those not loving TUI's. 

There is a basic administration API available today (v0.0.14-preview) that hopefully supports most things such an interface would need, at least as a starting point.

**Comment by Jonas-PFX** [comment]
I have been working a bit on this ! 😃 
Will hopefully have something ready within a few weeks.

**Comment by OlofBlomqvist** [comment]
merged #27 , thanks!
